obj-y 							+= adhocdeck.o
obj-y 							+= rangingProtocolStruct.o
obj-y 							+= rangingProtocolAlgo.o
obj-y 							+= rangingProtocolTask.o
obj-y 							+= rangingProtocolInit.o
obj-$(CONFIG_SWARM_FLOODING)   	+= floodingStruct.o
obj-$(CONFIG_SWARM_FLOODING)   	+= floodingAlgo.o